name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run sapper
      run: npm run dev
    - name: Run Cypress
      run: |
        cypress run --record --key d4d046a9-e025-4d49-9c5e-daebd7df64bd
    - name: Add remote origin
      run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Deploy to Heroku
      run: |
          git push heroku HEAD:master -f